package cc.samlab.mycity.datasourse

import cc.samlab.mycity.R
import cc.samlab.mycity.model.Category
import cc.samlab.mycity.model.Recommendation

object dataSource {
    val cityCatalog = listOf<Category>(
        Category(
            R.string.cat_1,
            R.drawable.tourist_attraction,
            listOf<Recommendation>(
                Recommendation(
                    R.string.attraction_1,
                    R.string.attraction_1_description,
                    R.drawable.waitan
                ),
                Recommendation(
                    R.string.attraction_2,
                    R.string.attraction_2_description,
                    R.drawable.lujiazui
                ),
                Recommendation(
                    R.string.attraction_3,
                    R.string.attraction_3_description,
                    R.drawable.wukang_building
                ),
                Recommendation(
                    R.string.attraction_4,
                    R.string.attraction_4_description,
                    R.drawable.xujiahui
                ),
                Recommendation(
                    R.string.attraction_5,
                    R.string.attraction_5_description,
                    R.drawable.jingan_temple
                )
            )
        ),

        Category(
            R.string.cat_2,
            R.drawable.restaurant_and_food,
            listOf<Recommendation>(
                Recommendation(
                    R.string.food_1,
                    R.string.food_1_description,
                    R.drawable.peace_hotel
                ),
                Recommendation(
                    R.string.food_2,
                    R.string.food_2_description,
                    R.drawable.starbucks1
                ),
                Recommendation(
                    R.string.food_3,
                    R.string.food_3_description,
                    R.drawable.found158
                )
            )
        ),

        Category(
            R.string.cat_3,
            R.drawable.shopping,
            listOf<Recommendation>(
                Recommendation(
                    R.string.shopping_1,
                    R.string.shopping_1_description,
                    R.drawable.east_nanjing_road_1
                ),
                Recommendation(
                    R.string.shopping_2,
                    R.string.shopping_2_description,
                    R.drawable.shanghai_akihabara
                ),
                Recommendation(
                    R.string.shopping_3,
                    R.string.shopping_3_description,
                    R.drawable.global_harbor
                ),
                Recommendation(
                    R.string.shopping_4,
                    R.string.shopping_4_description,
                    R.drawable.longemont
                ),
                Recommendation(
                    R.string.shopping_5,
                    R.string.shopping_5_description,
                    R.drawable.dapuqiao
                )
            )
        ),

        Category(
            R.string.cat_4,
            R.drawable.museum,
            listOf<Recommendation>(
                Recommendation(
                    R.string.museum_1,
                    R.string.museum_1_description,
                    R.drawable.shanghai_museum
                ),
                Recommendation(
                    R.string.museum_2,
                    R.string.museum_2_description,
                    R.drawable.ccp_site
                ),
                Recommendation(
                    R.string.museum_3,
                    R.string.museum_3_description,
                    R.drawable.sihang_warehouse
                )
            )
        ),

        Category(
            R.string.cat_5,
            R.drawable.public_transportation,
            listOf<Recommendation>(
                Recommendation(
                    R.string.transportation_1,
                    R.string.transportation_1_description,
                    R.drawable.nanpu_bridge
                ),
                Recommendation(
                    R.string.transportation_2,
                    R.string.transportation_2_description,
                    R.drawable.metro
                ),
                Recommendation(
                    R.string.transportation_3,
                    R.string.transportation_3_description,
                    R.drawable.south_railway_station
                ),
                Recommendation(
                    R.string.transportation_4,
                    R.string.transportation_4_description,
                    R.drawable.pvg
                ),
                Recommendation(
                    R.string.transportation_5,
                    R.string.transportation_5_description,
                    R.drawable.jinshanwei_station
                ),
                Recommendation(
                    R.string.transportation_6,
                    R.string.transportation_6_description,
                    R.drawable.ferry
                )
            )
        )
    )
}
